services:
  mongo:
    container_name: "mongodb"
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    env_file:
      - ./db/.env
    volumes:
      - database-v:/data/db
    networks:
      - dmcc-network

  api:
    container_name: "dmccserver"
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "7240"
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    networks:
      - dmcc-network

  client:
    container_name: "dmccclient"
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
      - mongo

    networks:
      - dmcc-network

volumes:
  dmccserver-node-modules:
    name: "dmcccserver-node-modules"
  database-v:
    name: "database-v"

networks:
  dmcc-network:
    driver: bridge
